Repository CMU-313/fall23-nodebb-debugdragons, pull requests merged in 2023-10, with the labels that each got.

#32 Added Type Assertions for src/user/index.js instead of translating to TS
  src/user/index.js
Labels: documentation

#38 Added sanity checks to src/topics/data.js
  src/privileges/topics.js
  src/topics/data.js
  src/topics/tools.js
  themes/nodebb-theme-persona/templates/partials/topics_list.tpl
Labels: documentation

#41 Sanity check for src/topics/create.js
  src/topics/create.js
Labels: documentation

#36 Added sanity checks to src/topics/tools.js
  src/topics/tools.js
Labels: documentation

#43 Added Automated Tests for Question Pinning Feature
  test/topics.js
Labels: enhancement

#44 Fixed lint issue and tester problems. Cleaned up code from other branches
  src/posts/create.js
  src/posts/index.js
  src/topics/create.js
  src/topics/data.js
  src/topics/posts.js
  test/topics.js
Labels: enhancement

#46 Added user guide for new features
  UserGuide.md
  test/topics.js
Labels: documentation

#47 Fixing after-merge bugs
  src/topics/posts.js
  themes/nodebb-theme-persona/templates/partials/topics_list.tpl
Labels: bug

#49 Made a few small changes to enhance experience for project 3
  UserGuide.md
Labels: documentation

#51 Added a very small change to ease experience for project 3
  UserGuide.md
Labels: documentation

#50 Modified a Type Assertion in Preparation for Project 3
  src/privileges/topics.js
Labels: bug
